blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/anneliset47/ml-pathogenicity.github.io/security/advisories/new
    about: Please report security issues privately.
